# Copyright (c) Meta Platforms, Inc. and affiliates. All Rights Reserved.
TRAIN:
  ENABLE: True
  DATASET: howto100m
  BATCH_SIZE: 16
  EVAL_PERIOD: 3
  CHECKPOINT_PERIOD: 3
  AUTO_RESUME: True
  LINEAR: True
  EPOCH_MUL: 2
DATA:
  PATH_TO_DATA_DIR: "/data/home/medhini/video-distant-supervision/data_csv/coin_step/"
  PATH_PREFIX: "/fsx/medhini/data/coin/all_videos"
  NUM_FRAMES: 8
  SAMPLING_RATE: 32
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 224
  INPUT_CHANNEL_NUM: [3]
  FD: 68.
  DECODING_BACKEND: 'ffmpeg'
  FIX_END: True
TIMESFORMER:
  ATTENTION_TYPE: 'divided_space_time'
  PRETRAINED_MODEL: '/data/home/medhini/video-distant-supervision/masked_step_modeling/checkpoints/checkpoint_epoch_00003.pyth'
  # PRETRAINED_MODEL: '/data/home/medhini/video-distant-supervision/TimeSformer_divST_8x32_224_HowTo100M_pretrained.pth'
  # PRETRANIED_MODEL: './step.pth'
SOLVER:
  BASE_LR: 0.005
  LR_POLICY: steps_with_relative_lrs
  STEPS: [0, 11, 14]
  LRS: [1, 0.1, 0.01]
  MAX_EPOCH: 15
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-4
  OPTIMIZING_METHOD: sgd
MODEL:
  MODEL_NAME: vit_base_patch16_224
  NUM_CLASSES: 778
  ARCH: vit
  LOSS_FUNC: cross_entropy
  DROPOUT_RATE: 0.5
  NUM_SEG: 12
  EXTRA_TR: '2-space'
  DROP_E: 0.1
  EXTRA_POS: True
  RET_HEAD: 1
  PRE_CLASSES: 10588
  HEAD_T: False
  RET_POS: True
TEST:
  ENABLE: True
  DATASET: howto100m
  BATCH_SIZE: 16
  NUM_ENSEMBLE_VIEWS: 4
  NUM_SPATIAL_CROPS: 1
DATA_LOADER:
  NUM_WORKERS: 10
  PIN_MEMORY: True
NUM_GPUS: 8
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: .
TENSORBOARD: 
  ENABLE: True
  LOG_DIR: 'step_forecasting'
