# Copyright (c) Meta Platforms, Inc. and affiliates. All Rights Reserved.
TRAIN:
  ENABLE: True
  DATASET: Epickitchens
  BATCH_SIZE: 16
  EVAL_PERIOD: 5
  CHECKPOINT_PERIOD: 5
  AUTO_RESUME: True
DATA:
  NUM_FRAMES: 32
  SAMPLING_RATE: 2
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 224
  INPUT_CHANNEL_NUM: [3]
  USE_RAND_AUGMENT: True
  RE_PROB: 0.0
  USE_REPEATED_AUG: False
  USE_RANDOM_RESIZE_CROPS: False
  COLORJITTER: False
  GRAYSCALE: False
  GAUSSIAN: False
EPICKITCHENS:
  VISUAL_DATA_DIR: "PATH To EPIC-Kitchen-100 videos"
  ANNOTATIONS_DIR: "PATH To epic-kitchens-100-annotations/"  
TIMESFORMER:
  ATTENTION_TYPE: 'divided_space_time'
  PRETRAINED_MODEL: 'PATH to pretrained model'
SOLVER:
  BASE_LR: 1e-4
  LR_POLICY: steps_with_relative_lrs
  LRS: [1, 0.1, 0.01]
  STEPS: [0, 30, 40]
  MAX_EPOCH: 50
  MOMENTUM: 0.9
  WEIGHT_DECAY: 5e-2
  WARMUP_EPOCHS: 0.0
  OPTIMIZING_METHOD: adamw
MODEL:
  MODEL_NAME: vit_base_patch16_224
  NUM_CLASSES: 97
  ARCH: vit
  LOSS_FUNC: cross-entropy
  DROPOUT_RATE: 0.5
MIXUP:
  ENABLED: True
  ALPHA: 0.1
TEST:
  ENABLE: True
  DATASET: Epickitchens
  BATCH_SIZE: 16
  NUM_ENSEMBLE_VIEWS: 10
  NUM_SPATIAL_CROPS: 3
DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True
NUM_GPUS: 8
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: .